<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
$this->title = 'Terms';
$script = <<< JS
$(document).ready(function(){	
switch (window.location.pathname) {
    case '/terms':
        $('#main_nav_bar').addClass('tech')
    case '/terms':
    case '/terms':
        $('#main_nav_bar').addClass('tech')
}
});
JS;
$this->registerJs($script);
?>

<div class="site-terms">
  <div class="container">
    <div class="row">
      <div class="col-md-12 about_us_text">
        <h1 class="text-center heading-margins">
          <?= Html::encode($this->title) ?>
        </h1>
        <p> 1.	These Terms of Use apply to Wizerd.com, as well as any other affiliated Sites, digital services, or applications on which a link to these Terms of Use appears (collectively, the Site). As used herein, the Owner refers to Wizerd.com. <br />
          2.	These Terms of Use apply to all visitors (which shall include persons and representatives of all legal entities, whether such representatives are persons or digital engines of a kind that crawls, indexes, scrapes, copies, stores or transmits digital content).<br />
          3.	These Terms of Use may be modified at any time and from time to time; the date of the most recent revisions will appear on this page, so check back periodically. You agree that your use of the Site is subject to the Terms of Use then in effect. Continued access to the Site by you following any modification in the Terms of Use will constitute your acceptance of the Terms of Use as modified. If you do not agree to be bound by all of the terms set forth below, do not use this Site.<br />
          4.	WEBSITE PROVIDED AS-IS, AS-AVAILABLE<br />
          A.	The materials comprising the Site are provided by the Owner as a service to you for your noncommercial, personal use on an as-is, as-available basis. You acknowledge that you are using the Site at your own risk.<br />
          B.	Owner assumes no responsibility for any errors or omissions in the materials comprising the Site. The Owner makes no commitment to update the information on the Site. No advice or information given by the Owner or any other party on the Site shall create any warranty or liability. Further, Owner is not responsible for any content transmitted or posted to the Site by a third party. Any such third party content does not necessarily represent the opinions, beliefs, or positions of the Owner. <br />
          C.	Owner periodically schedules system downtime for maintenance and other purposes. Unplanned outages also may occur. Owner shall have no liability for the resulting unavailability of the Site or for any loss of data or transactions caused by planned or unplanned system outages, or any outages of webhost providers.<br />
          D.	Owner makes no, and expressly disclaims any, representations or warranties, express or implied, regarding the Site, including, without limitation, any implied warranties of merchantability or fitness for a particular purpose.  Owner makes no, and expressly disclaims any, warranties, express or implied, regarding the correctness, accuracy, completeness, timeliness, and reliability of the text, images, graphics, links to other Sites and any other items on the Site or accessed via the Site, or that the Site will be uninterrupted, error-free or free of viruses or other harmful components. Under no circumstances shall the Owner, its affiliates, or any of their respective partners, officers, directors, employees, agents or representatives be liable for any damages whatsoever, whether direct, indirect, special or consequential damages for lost revenues, lost profits, or otherwise, arising from or in connection with this Site, the materials contained herein, or the Internet generally. These disclaimers of warranties and limitations of liability shall apply to the fullest extent permitted by applicable law.<br />
          E.	The Owner is not responsible for, and does not control, any third party content or advertisements that are posted on this Site, nor does it take any responsibility for the goods or services provided by its advertisers. <br />
          5.	COPYRIGHT<br />
          A.	All materials contained in the Site, including software, text, videos, photographs, images, sound files and other materials (collectively, Content), are protected by copyright laws, and may not be reproduced, republished, distributed, transmitted, sold, displayed, broadcast or otherwise exploited in any manner without the express prior written permission of either the Owner or, in the case of content licensed by the Owner from third parties, the entity that is credited as the copyright holder of such licensed content. Unauthorized use of Content may violate copyright, trademark and other laws. You have no rights in or to the Content and you may not use the Content except as permitted under these Terms of Use. You may download freely-accessible Content (one copy per page) from the Site for your personal and non-commercial use only, without altering or removing any trademark, copyright or other notice from Content. Any third party materials transmitted or posted to the Site become the copyrighted property of the Owner, and may be used, reproduced, published, distributed, transmitted, sold, displayed, broadcast or otherwise exploited by the Owner. If you violate these Terms of Use, your permission to access the Site terminates and you must immediately destroy any copies you have made of the Content.<br />
          B.	Owner does not permit infringement of intellectual property rights on the Site. If you believe that any Content on the Site infringes your copyright or other intellectual-property rights, you may notify the Owner by providing the information required by the Online Copyright Infringement Liability Limitation Act section of the Digital Millennium Copyright Act, 17 U.S.C. 512 (c)(3), to the Owner at support@wizerd.com.<br />
          6.	IMPERMISSIBLE USES OF THE WEBSITE<br />
          A.	You agree not to: (a) systematically retrieve data or other Content from the Site to create or compile, directly or indirectly, a collection, compilation, database, directory or the like, whether by manual methods, through the use of bots or otherwise; (b) use any trademarks, trade names or other intellectual property of the Owner or any other party from the Site as meta tags on other Sites, to disparage any party or in any manner that may damage any goodwill in the intellectual property; and (c) collect usernames and/or email addresses of other users by electronic or other means for the purpose of sending unsolicited email or other communications. <br />
          B.	The following activities on the Site are expressly prohibited: (i) any use of the Site, which in Owner's sole judgment, degrades the reliability, speed, or operation of the Site or any underlying hardware or software thereof, and (ii) any use of the Site which is unlawful or in violation of these Terms of Use.<br />
          C.	Owner, and all other trademarks, trade names, logos and other intellectual property owned by the Owner are the property of the Owner and cannot be used without the Owner's express prior written permission.<br />
          7.	USER CONTENT<br />
          A.	Owner may provide users, which includes advertisers, an opportunity to transmit or post text, videos, photographs, images, sound files and/or other content to the Site (collectively, User Content) and may provide for the hosting, sharing and/or publishing of such User Content. Owner does not necessarily endorse, support, sanction, encourage, or agree with User Content and expressly disclaims any and all liability in connection with any User Content.<br />
          B.	You shall not transmit or post any User Content that: (i) is unlawful, threatening, harassing, abusive, false, inaccurate, deceptive, misleading, offensive, distasteful, inappropriate, libelous, defamatory, obscene, vulgar, pornographic, profane, indecent, invasive of another's privacy or harmful to minors in any way; (ii) constitutes or encourages conduct that would constitute a criminal offense, give rise to civil liability, or otherwise violate and local, state, national, or international law; (iii) is copyrighted, protected by trade secret, patent, trademark or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to submit or post the material and to grant Owner all of the license rights granted herein; (iv) refer derisively to the goods or services of others; (v) includes any disruptive elements that may damage or interfere with the Site such as computer viruses, bots, worms, bombs, or trojan horses; (vi) impersonates another person; (vii) includes any person's full name or personal or identifying information without that person's authorization; or (viii) violates the law or otherwise violates these Terms of Use.<br />
          C.	In connection with any User Content you submit, affirm, represent, and/or warrant that: (i) you own or have the necessary licenses, rights, consents, and permissions to use and authorize the Owner to use all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all User Content to enable inclusion and use of the User Content in the manner contemplated by the Site and these Terms of Use; (ii) you have the written consent, release, and/or permission of each and every identifiable individual person in the User Content to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of the User Content in the manner contemplated by the Site and these Terms of Use; and (iii) it complies with these Terms of Use.<br />
          D.	You understand that all User Content is the sole responsibility of the person who transmits or posts that User Content. This means that you, and not Owner, are entirely and solely responsible for all User Content that you transmit or post and for the consequences of Owner publishing such User Content. Owner does not and cannot review the User Content transmitted or posted by users and is not responsible for such content. However, Owner shall have the right, but not the obligation, to refuse, delete, move, remove, or edit any User Content that violates these Terms of Use or is otherwise objectionable, as determined by the Owner in Owners sole discretion and without notice. Any specific complaints regarding User Content must be directed to support@wizerd.com, and any promise by Owner to investigate, delete, remove, or otherwise edit any User Content shall be non-binding unless expressly provided in writing by Owner.<br />
          E.	You agree to indemnify the Owner and its affiliates, and each of their respective partners, officers, directors, employees, agents and representatives, against, and to hold each of them harmless from, any and all claims and liabilities (including attorney's fees) that may arise from your use of the Site, your transmission or posting of User Content, your unauthorized use of material obtained from the Site, your breach of these Terms of Use, your violation of any law, regulation or any right of any other person or entity, and any unauthorized use of your account or password. Owner reserves the right to assume the exclusive defense and control of any matter that is subject to indemnification under this section. In such case, you agree to cooperate with any reasonable requests assisting our defense of such matter.<br />
          F.	By transmitting or posting User Content, you grant Owner the perpetual, non-terminable, worldwide, nonexclusive, royalty-free, and transferable right and license to use, reproduce, edit, remove, modify, publish, transmit, display, distribute, have distributed, promote, perform, and prepare derivative works of, all or any potion of such User Content in any form, in any medium now existing or hereinafter invented for any purpose, including commercial uses. You waive any moral rights you may have in the User Content. You also grant each user of the Site a non-exclusive license to access your User Content through the Site, and to use, reproduce, distribute, prepare derivative works of, display and perform such User Content as permitted through the functionality of the Site and under these Terms of Use.<br />
          8.	USER ACCOUNTS AND PASSWORDS<br />
          A.	To use certain optional features and functions of the Site, users may be given the opportunity to create user accounts with passwords. You agree to maintain the confidentiality of your user account information and password(s) and you agree not to use your user account(s) or password(s) for any unauthorized purpose. By creating any user account, you represent, warrant and certify that you are at least thirteen (13) years of age.<br />
          B.	You are responsible for actions undertaken by those using your user account(s) and password(s). Owner, in its sole discretion, may suspend or terminate your user account(s) for any reason without notice, including but not limited to if you or anyone using your user account(s) or password(s) violates or attempts to violate these Terms of Use.<br />
          C.	Owner may, in appropriate circumstances, terminate your user account(s), if you are determined to be a repeat infringer. You may be determined to be a repeat infringer if the Owner determines that you have posted or transmitted infringing User Content more than once.<br />
          9.	PRIVACY POLICY<br />
          The Owner has established a Privacy Policy as modified from time to time, which explains how information is collected on the Site and used. The Privacy Policy is part of these Terms of Use and is incorporated herein by reference.<br />
          10.	PLEASE BE ADVISED THAT OWNER IS NOT A PARTY TO ANY TRANSACTION BETWEEN BUYER AND SELLER.  The Site acts as a venue to allow an advertiser of this Site (each, an advertiser) to offer for sale, in a variety of pricing formats, a specific product or service to potential buyers.  Owner is not involved in the actual transaction between buyers and sellers even though Owner may from time to time provide tools that enable a visitor to the Site to enter into a transaction directly with the advertiser. As a result, the quality, safety or legality of the products and services advertised, the truth or accuracy of the products and services listed (including the content thereof or any product and service review), the ability of users to buy products and services, the value or fulfillment of any complementary add-ons or features that may be offered in connection with any product or service advertised in an effort to attract advertising, such as complementary gift cards or other complementary products or services or the ability of users to pay for products and services are solely the responsibility of the users and advertisers.<br />
          11.	PERSONAL USE <br />
          A.	Although Owner may charge a fee to advertisers to advertise their products and services on the Site, Owner does not charge visitors to access the Site and research products and uses. Accordingly, Owner grant advertisers a limited, revocable, non-exclusive license to access the Site to, as applicable, advertise products and services for sale or research, view or make legitimate inquiries to users regarding their interest in particular products and for their personal use, all in accordance with these Terms. Any other use of the Site is expressly prohibited. Importantly, this license does not include any right of collection, aggregation, copying, duplication, display or derivative use of the Site nor any right of use of data mining, robots, spiders or similar data gathering and extraction tools without Owner's prior written permission.<br />
          12. 	CHANGES TO SITE<br />
          Owner may change, suspend or discontinue any aspect of the Site at any time, including the availability of any Site features, database, or content. Owner may also impose limits on certain features or services or restrict your access to parts or the entire Site without notice or liability.<br />
          13. 	DATA TRANSMITTAL<br />
          Each user acknowledges and agrees that, regardless of such user's physical location, Owner may store and process any data transmitted to the Site from such user at locations both within and outside of the United States.<br />
          14. 	IDENTITY VERIFICATION<br />
          A.	User verification on the Internet is difficult and Owner cannot and does not confirm each user's purported identity. Owner encourages you to communicate directly with a prospective buyer or user through the tools available on the Site.<br />
          B.	If you have a password and online ID, you agree to (i) keep your password and online ID secure and strictly confidential, providing it only to authorized users of your account, (ii) instruct each person to whom you give your online ID and password that he or she is not to disclose it to any unauthorized person, (iii) notify Owner immediately and select a new online ID and password if you believe your password may have become known to an unauthorized person, and (iv) notify Owner immediately if you are contacted by anyone requesting your online ID and password.  When you give someone your online ID and online password, you are authorizing that person to access and use your account, and you are responsible for any and all transactions that person performs while using your account, even those transactions that are fraudulent or that you did not intend or want performed. <br />
          C.	EACH USER ACKNOWLEDGES AND AGREES THAT: (i) NEITHER THE SITE NOR ANY OF ITS AFFILIATES WILL HAVE ANY LIABILITY TO ANY USER FOR ANY UNAUTHORIZED TRANSACTION MADE USING ANY USER'S PASSWORD THAT OCCURS BEFORE SUCH USER HAS NOTIFIED US OF POSSIBLE UNAUTHORIZED USE OF SUCH PASSWORD AND OWNER HAVE HAD A REASONABLE OPPORTUNITY TO ACT ON THAT NOTICE; AND (ii) THE UNAUTHORIZED USE OF YOUR ONLINE ID AND PASSWORD COULD CAUSE YOU TO INCUR LIABILITY TO BOTH THE SITE AND OTHER USERS.  Further, Owner may suspend or cancel your listing or online access at any time even without receiving notice from you if Owner suspects that your password is being used in an unauthorized or fraudulent manner.<br />
          D.	Owner does not tolerate spam. Therefore, without limiting the foregoing, you are not licensed to add a Site user without the Owner's express consent.<br />
          15. 	RELEASE<br />
          IN THE EVENT THAT YOU HAVE A DISPUTE WITH ONE OR MORE OTHER USERS OR ADVERTISERS OF THE SITE (INCLUDING, WITHOUT LIMITATION, ANY DISPUTE BETOWNEREN USERS REGARDING ANY TRANSACTION), YOU HEREBY AGREE TO RELEASE, REMISE AND FOREVER DISCHARGE OWNER OF THE SITE, EACH OF THEIR RESPECTIVE AGENTS, DIRECTORS, OFFICERS, EMPLOYEES, AND ALL OTHER RELATED PERSONS OR ENTITIES FROM ANY AND ALL MANNER OF RIGHTS, CLAIMS, COMPLAINTS, DEMANDS, CAUSES OF ACTION, PROCEEDINGS, LIABLITIES, OBLIGATIONS, LEGAL FEES, COSTS, AND DISBURSEMENTS OF ANY NATURE WHATSOEVER, WHETHER KNOWN OR UNKNOWN, WHICH NOW OR HEREAFTER ARISE FROM, RELATE TO, OR ARE CONNECTED WITH SUCH DISPUTE AND/OR YOUR USE OF THE SITE. IF YOU ARE A CALIFORNIA RESIDENT,YOU WAIVE CALIFORNIA CIVIL CODE SECTION 1542, WHICH SAYS: "A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH, IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR."<br />
          16. 	INDEMNITY<br />
          YOU HEREBY AGREE TO INDEMNIFY, DEFEND AND HOLD OWNER OF THE SITE (COLLECTIVELY, THE INDEMNIFIED PARTIES) HARMLESS FROM AND AGAINST ANY AND ALL LIABILITY AND COSTS INCURRED BY THE INDEMNIFIED PARTIES IN CONNECTION WITH ANY CLAIM ARISING OUT OF YOUR USE OF THE SITE (INCLUDING, WITHOUT LIMITATION, ANY DISPUTE BETWEEN USERS REGARDING ANY TRANSACTION), ANY CONTENT POSTED BY YOU TO THE SITE OR ANY BREACH BY YOU OF THESE TERMS OR THE REPRESENTATIONS, WARRANTIES AND COVENANTS MADE BY YOU HEREIN, INCLUDING, WITHOUT LIMITATION, ATTORNEYS' FEES AND COSTS. YOU SHALL COOPERATE AS FULLY AS REASONABLY REQUIRED IN THE DEFENSE OF ANY CLAIM. OWNER RESERVES THE RIGHT, AT OUR OWN EXPENSE, TO ASSUME THE EXCLUSIVE DEFENSE AND CONTROL OF ANY MATTER OTHERWISE SUBJECT TO INDEMNIFICATION BY YOU AND YOU SHALL NOT IN ANY EVENT SETTLE ANY MATTER WITHOUT OUR WRITTEN CONSENT.<br />
          17.	DISCLAIMERS<br />
          A.	All data, software, and documentation in this Web site are provided "as is" without warranty of any kind, either expressed or implied. The owner of Wizerd.com, its affiliates, agents and licensors cannot and do not warrant the accuracy, completeness, non-infringement, merchantability or fitness of any information contained on this site.<br />
          B,	The views and opinions of authors published on this site do not necessarily reflect those of Wizerd.com.<br />
          C.	Reference to any specific commercial products, processes, or services by trade name, trademark, manufacturer, or otherwise does not necessarily constitute or imply its endorsement or recommendation by Wizerd.com. Nor shall any information or statements contained on this server be used for the purposes of advertising, or to imply an endorsement or recommendation.<br />
          D.	With respect to any documents available from this server, neither Wizerd.com nor any of its employees make any warranty, express or implied, including but not limited to the warranties of merchantability and fitness for a particular purpose. Further, neither Wizerd.com nor any of its employees assume any legal liability or responsibility for the accuracy, completeness, or usefulness of any information, apparatus, product or process disclosed; nor do they represent that its use would not infringe privately owned rights.<br />
          E.	This disclaimer of liability applies to any damages or injury caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction or unauthorized access to, alteration of, or use of record, whether for breach of contract, tortious behavior, negligence, or under any other cause of action. You specifically acknowledge that Wizerd.com is not liable for your defamatory, offensive, infringing or illegal materials or conduct, or that of third parties, and Wizerd.com reserves the right to remove such materials from the Website of Wizerd.com without liability.<br />
          F.	The information published on this web site was valid at the time of publication. Wizerd.com reserves the right to make changes and improvements at any time and without notice, and assumes no liability for damages incurred directly or indirectly as a result of errors, omissions or discrepancies.<br />
          G.	The Website of Wizerd.com contains links to and frames of sites, which are not maintained by Wizerd.com. While we try to include only links to or frames of those sites which are in good taste and safe for our visitors, we are not responsible for the content of those sites and cannot guarantee that sites will not change without our knowledge, and inclusion of such links and frames in the Website of Wizerd.com does not imply Wizerd.com's endorsement of the linked or framed sites or their content.<br />
          H.	By sending us a message in the e-mail area, you agree to have it along with your name posted for public viewing both here and in other promotional and advertising materials of Wizerd.com without compensation. All messages that are posted here represent the opinions of other users of Wizerd.com and do not represent the ideas or opinions of Wizerd.com. You may copy them as much as you like for personal use, but redistribution in any way requires the permission of Wizerd.com. In consideration of this authorization, you agree that any copy of this information which you make shall retain all copyright and other proprietary notices contained here in this Website.<br />
          I.	The search engine and access to this website of Wizerd.com is provided to you at no cost, as is. All efforts will be used to maintain the site but you should not assume that it is error-free or is suitable for the particular purpose that you intended when gaining access to the site. Wizerd.com is not responsible for the results of any defects that may be found to exist in the site or any lost profits or other consequential damages that may result from such defects.<br />
          J.	Wizerd.com's search engine refers sites and information located worldwide throughout the Internet. Because Wizerd.com has no control over such sites and information, it makes no guaranties as to those sites and information, including: (1) the accuracy, currency, content, or quality of the search results, or (2) whether the search may locate any unintended and objectionable content.<br />
          18.	Wizerd.com respects the intellectual property interests of other parties. If you believe that your work appears on this Website in a way that constitutes copyright infringement, you may notify Wizerd.com and provide the following information:<br />
          A.	An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest;<br />
          B. 	A copy of the copyrighted work that you claim has been infringed, or a description of the copyrighted work, including the URL (i.e., web page address) of the location where the copyrighted work exists;<br />
          C. 	Identification of the URL or other specific location on the site of Wizerd.com where the material that you claim is infringing is located;<br />
          D.	A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;<br />
          E.	A statement by you, made under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf; and <br />
          F.	Your address, telephone number, and e-mail address.<br />
          19.	To the fullest extent permitted by law, in no event shall Owner or any of its directors, employees or agents have any liability whatsoever to any person for any direct or indirect loss, liability, cost, claim, expense or damage of any kind, whether in contract or in tort, including negligence, or otherwise, arising out of or related to the use by you of all or part of this web site or the Software.<br />
          20.	INTELLECTUAL PROPERTY RIGHTS 
          Owner retains all right, title and interest (including copyrights, trademarks, patents, as well as any other intellectual property or other right) in all information and content (including all text, data, graphics and logos) on the this Website.<br />
          21.	TRADEMARKS<br />
          The trademarks, service marks and logos used and displayed on the Site are registered trademarks and service marks of Owner. You are not granted, expressly or by implication, estoppels or otherwise, any license or right to use any trademark, service mark or logo used or displayed on the Site, without the express written permission of Owner. <br />
          22.	PATENTS<br />
          The technology and products, including products that may from time to time be available on the Site, may be protected by one or more United States patents. International patents and patents pending may also be applicable in their respective countries.<br />
          23.	GOVERNING LAW<br />
          This Agreement shall be governed by, construed, and enforced in accordance with the laws of the State of California.<br />
          24. NOTICES<br />
          Except as explicitly stated otherwise, any notices shall be given (in the case of you contacting Owner) by email to support@wizerd.com. If Owner needs to send you notice, Owner may send such notice to the email address you provide to Owner during the registration process. Notice shall be deemed given upon receipt or 24 hours after email is sent, unless the sending party is notified that the email address is invalid. Alternatively, Owner may give you notice by certified mail, postage prepaid and return receipt requested, to any address provided to Owner during the registration process. In such case, notice shall be deemed given three days after the date of mailing.<br />
          25. YOUR RECORD OF THESE TERMS|<br />
          Owner does not separately file the terms entered into by each user of the Site. Please make a copy of these terms for your records by printing and/or saving a downloaded copy of the terms on your personal computer.<br />
          26.	ENTIRE AGREEMENT<br />
          This Agreement shall constitute the entire agreement between the parties and any prior understanding or representation of any kind preceding the date of this Agreement shall not be binding upon either party except to the extent incorporated in this Agreement.<br />
          27. 	ADVERTISER ELIGIBILITY; ACCURACY OF INFORMATION; REPRESENTATIONS; WARRANTIES<br />
          A.	Uses of the Site may only be advertisers who can form legally binding contracts under applicable law. If you are registering as a business entity, you represent that you have the authority to bind the entity to this Agreement.<br />
          B.	Each advertiser further represents and covenants that any information submitted to the Site during such advertisers registration with the Site shall be true and correct. User and Advertiser further agree to provide notice to the Site by submitting a form regarding any updates to any such contact information previously submitted by advertiser to the Site. As a condition of listing each advertiser agrees to provide, such proof of identity, proof of ownership, and proof of right to list as Owner may request.<br />
          C.	Advertiser is solely responsible for any legal liability arising out of or relating to the advertising information. Advertiser represents and warrants to Owner that it has full authority to provide and use the advertising information as contemplated by these Terms of Use, and that such provision and use of the advertising information does not and will not violate any copyrights, trademarks, trade secrets or other proprietary rights of any third party or create any liability to any third party. Advertiser further warrants that the advertising information does not contain any matter that is defamatory or which may cause injury or result in damage to any third party and that the advertising information does not contain any matter that is false or deceptive. <br />
          D.	Advertiser also represents and warrants that it will comply with all applicable laws and rules or regulations regarding conduct and advertising in its performance under these Terms of Use. Advertiser acknowledges that any breach of Advertiser's representations and warranties in these Terms of Use is a material breach of these Terms of Use. Advertiser shall defend, indemnify and hold harmless Owner from and against any and all third-party claims, actions, causes of action, liabilities, damages, costs, and expenses, including attorneys' fees, arising out of or related to any facts or alleged facts which, if true, would constitute a breach of such representations or warranties.  Third-party claims also include governmental claims, arising out of Advertiser's advertising information as well as the conduct of the Advertiser. Advertiser also represents and warrants that it will comply with the Terms of Use and Privacy Statement detailed on Wizerd.com, and with the Terms detailed on Wizerd.com.<br />
          28. CONTENT, LAYOUT AND COPY<br />
          A.	Owner reserves the right to determine in Owner's sole discretion the final design, layout and functionality of the Site, which is subject to change from time to time without notice.<br />
          B.	Owner reserve the right, in Owner's sole discretion, to review and edit copy or amend the content, layouts, videos, or photographs supplied by any advertiser. All content and copy edits submitted by advertisers are subject to review and approval by Owner.<br />
          C.	Notwithstanding Owner's right to edit and amend the content, copy, videos, and photographs, Owner does not accept and Owner shall not have any liability for any loss or damage resulting from the design or positioning of the copy, properties, content, videos, and/or photographs or any change made to any content, video, photograph or copy submitted by any advertiser or edited or amended by Owner.<br />
          29. PHOTOGRAPHS<br />
          A.	All printed (paper based) photographs submitted by an advertiser will be discarded after Owner has scanned the same into Owner's electronic database. Regretfully, Owner is unable to return such photographs to you or retain paper copies in Owner's files.<br />
          B.	Owner will use reasonable efforts to reproduce faithfully any video or photograph submitted, but Owner is not responsible for any loss or damage or harm otherwise resulting from any defect in this regard.<br />
          C.	By submitting a video or photograph either electronically through the Site or by mailing a paper photograph to Owner's offices, the advertiser represents and warrants that:
          It holds all intellectual property rights with respect to each submitted video or photograph or has secured from the copyright holder all rights necessary for the video or photograph to be used in an online advertisement, That any people in the video or photograph have given permission for their likeness to be displayed in an online advertisement, That the video or photograph accurately and fairly represents the subject of the video or photograph and has not been altered in any manner that would mislead a viewer of that video or photograph, and That it will indemnify and hold harmless the Owner's of the Site from any cause of action arising from any misrepresentation with respect to any and all the videos or photographs so submitted.<br />
          D.	Each advertiser agrees that Owner may reproduce in whole or in part any videographic or photographic material supplied by such advertiser in the promotion of either such advertiser's property or the promotion of the Site.<br />
          E.	It is the advertiser's responsibility to obtain reproduction permission for all videographic or photographic and other material used in their advertisements. The advertiser warrants that he is the owner of the copyright in such material or is authorized by the owner thereof to grant to use the rights therein contained.<br />
          30. HYPERTEXT LINKS<br />
          Owner reserves the right to refuse hypertext links to, or addresses of, other websites from advertisers' pages, and to remove links or addresses without notice at Owner's sole discretion. Further, Owner reserves the right to charge for hypertext links at any time.<br />
          31. FEEDBACK<br />
          Any entries in the Feedback section of any advertiser's listing must be genuine comments from users who have purchased the products or services advertised. <br />
          32. SUBSTITUTION OF PRODUCT OR SERVICE<br />
          Each advertisement may only relate to a specific product or service. The product or service in an advertisement may not be substituted by another product or service. If an advertiser submits changes to an existing listing that, if approved, would substantially alter the listing to make it that of another product or service, then Owner has the right to terminate the listing and may choose, in Owner's sole discretion, and to retain any fees associated with the term of the previously existing listing as compensation for the violation of this condition.<br />
          33. ADVERTISING MORE THAN ONE PRODUCT OR USE ON ONE ADVERTISEMENT<br />
          Each advertisement on the Site displays an individual and uniquely identified product or service available. The listing specifically cannot be a mere example of products or services. Only one product or service can appear on each advertisement. Owner reserves the right to amend the copy or remove any advertisement when more than one product or service is described in such advertisement, and may choose, in Owner's sole discretion to retain any fees associated with the initial term of such non-conforming listing as compensation for the violation of this condition.<br />
          34. 	DISABLING OF LISTINGS<br />
          A.	Owner reserve the right to refuse in Owner's sole discretion any advertisement submitted to Owner either through Owner's online submission process or sent to Owner's offices for Owner to load or post onto the Site. Owner may refuse to publish the advertisement for any reason, and each current or prospective advertiser expressly agrees to release and hold Owner harmless from any loss or liability that may arise from such a decision.<br />
          B.	If, in Owner's sole discretion, any advertiser submits unsuitable material to the Site or into Owner's database, persistently misuses the Site or the online systems, or is in material breach of these Terms, Owner reserves the right to remove immediately such advertiser's property from the Site without refund.<br />
          C.	If Owner becomes aware of or receives a complaint from any person or entity regarding an advertiser's listing or practices that, in Owner's sole discretion, warrants the immediate removal of such advertiser's allegedly offensive listing from the Site (for example, and without limitation, if an advertiser engages in any practice that, in Owner's sole discretion, would be considered unfair within the industry, or if Owner receives a complaint that any listing's content infringes on the rights of a third party), then Owner may immediately remove the allegedly offensive listing from the Site without notice to the advertiser and without refund while Owner investigates the basis for the complaint. If Owner concludes, in Owner's sole discretion, that any such complaint is meritorious, then Owner may permanently remove the offensive listing from the Site without notice to the advertiser.<br />
          D.	If any advertiser is in breach of these Terms or its obligations then Owner may immediately remove such advertiser's listing from the Site without notice to the advertiser and without refund.<br />
          35. TRANSFER OF LISTING<br />
          No listing may be transferred to another party until the completion of the advertising contract or Owner may, at Owner's discretion, charge a reasonable transfer fee.<br />
          36.	SEVERABILITY<br />
          The invalidity of any portion of this Agreement will not and shall not be deemed to affect the validity of any other provision. If any provision of this Agreement is held to be invalid, the parties agree that the remaining provisions shall be deemed to be in full force and effect as if they had been executed by both parties subsequent to the expungement of the invalid provision. <br />
          37.	NO WAIVER<br />
          The failure of either party to this Agreement to insist upon the performance of any of the terms and conditions of this Agreement, or the waiver of any breach of any of the terms and conditions of this Agreement, shall not be construed as subsequently waiving any such terms and conditions, but the same shall continue and remain in full force and effect as if no such forbearance or waiver had occurred.<br />
          38. MANDATORY ARBITRATION<br />
          Any dispute under this Agreement shall be required to be resolved by binding arbitration of the parties hereto. The arbitration shall be governed by the rules of the American Arbitration Association then in force and effect. The parties agree that this Agreement will be governed by and construed and interpreted in accordance with the laws of the State of California.<br />
          39. ATTORNEY'S FEES<br />
          In any action, arbitration or proceeding to enforce, preserve, or protect any right or benefit under these Terms of Use, the prevailing party in each such action or proceeding shall be entitled, in addition to any and all other relief granted by a court or arbitrator, to an award in such action or proceeding of the amount of its attorneys' fees, arbitration costs and other fees reasonably incurred therein.<br />
          40.	ENTIRE AGREEMENT<br />
          This Agreement shall constitute the entire agreement between the parties and any prior understanding or representation of any kind preceding the date of this Agreement shall not be binding upon either party except to the extent incorporated in this Agreement.<br />
          41.	In this Agreement, any reference to a party includes that party's heirs, executors, administrators, successors and assigns, singular includes plural and masculine includes feminine.<br />
        </p>
      </div>
    </div>
  </div>
</div>
<!--./site-terms-->