<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "field_value".
 *
 * @property integer $id
 * @property integer $tier_id
 * @property integer $field_id
 * @property integer $kw_group_id
 * @property string $value
 *
 * @property Field $field
 * @property Tier $tier
 */
class FieldValue extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'field_value';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [
                [
                    'tier_id',
                    'field_id'
                ],
                'required'
            ],
            [
                [
                    'tier_id',
                    'field_id'
                ],
                'integer'
            ],
            [
                ['value'],
                'string',
                'max' => 1000
            ],
            [
                [
                    'tier_id',
                    'field_id'
                ],
                'unique',
                'targetAttribute' => [
                    'tier_id',
                    'field_id'
                ],
                'message' => 'The combination of Tier ID and Field ID has already been taken.'
            ],
            [
                ['field_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => Field::className(),
                'targetAttribute' => ['field_id' => 'id']
            ],
            [
                ['tier_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => Tier::className(),
                'targetAttribute' => ['tier_id' => 'id']
            ],
        ];
    }

    public function beforeSave($insert)
    {
        // if(strlen($this->value)>0)
        if (!$key = Keyword::createKeywords($this->value, $this->kw_group_id)) {
            return false;
        } else {
            $this->kw_group_id = $key;
        }

        $this->tier->createTKW();


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        $oldKWG = KeywordGroup::find()
            ->where('id=:id', ['id' => $this->kw_group_id])
            ->one();
        if ($oldKWG !== null) {
            $oldKWG->delete();
        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tier_id' => 'Tier ID',
            'field_id' => 'Field ID',
            'value' => 'Value',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getField()
    {
        return $this->hasOne(Field::className(), ['id' => 'field_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTier()
    {
        return $this->hasOne(Tier::className(), ['id' => 'tier_id']);
    }
}
